# Generated by Django 5.2.8 on 2025-12-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_client_email_invoice_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manual_service_ame',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
