# Generated by Django 5.2.8 on 2025-12-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_manual_service_ame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='manual_service_ame',
            new_name='manual_service_name',
        ),
    ]
