# Generated by Django 5.2.8 on 2025-12-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_rename_manual_service_ame_invoice_manual_service_name'),
        ('quotes', '0003_alter_quote_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manual_cleint_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_client_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='quotes.quote'),
        ),
    ]
