# Generated by Django 5.2.8 on 2025-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_manual_cleint_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='manual_cleint_phone',
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_client_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
