# Generated by Django 5.2.8 on 2025-11-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='Online Payment', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='invoices.invoice')),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
