# Generated by Django 5.2.8 on 2025-12-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('check', 'Check'), ('online', 'Online Payment')], default='bank_transfer', max_length=50),
        ),
    ]
