# Generated by Django 5.2.8 on 2025-12-05 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_client_email_invoice_client_name_and_more'),
        ('receipts', '0003_receipt_subtotal_receipt_tax_amount_receipt_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='invoices.invoice'),
        ),
        migrations.AlterModelTable(
            name='receiptlineitem',
            table='receipt_line_items',
        ),
    ]
