# Generated by Django 5.2.8 on 2025-11-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Company', max_length=200)),
                ('company_email', models.EmailField(default='info@company.com', max_length=254)),
                ('company_phone', models.CharField(default='+1234567890', max_length=20)),
                ('company_address', models.TextField(default='123 Business St, City, Country')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('email_footer', models.TextField(default='Thank you for your business!')),
                ('quote_email_template', models.TextField(blank=True)),
                ('invoice_email_template', models.TextField(blank=True)),
                ('payment_instructions', models.TextField(default='Please make payment within 30 days.')),
                ('bank_details', models.TextField(blank=True)),
                ('admin_notification_email', models.EmailField(default='admin@company.com', max_length=254)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=20)),
                ('pdf_primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('pdf_secondary_color', models.CharField(default='#64748b', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
