# Generated by Django 5.2.8 on 2025-11-28 14:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('design', 'UI/UX Design'), ('consulting', 'Consulting'), ('marketing', 'Digital Marketing'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quotes/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Invoice')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
