# Generated by Django 5.2.8 on 2025-12-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='service_type',
            field=models.CharField(choices=[('space_beautification', 'Space Beautification & Interior Decoration'), ('skimming_wall_prep', 'Skimming & Wall Preparation'), ('space_planning', 'Space Planning & Concept Development'), ('material_consultation', 'Material Supply & Consultation'), ('painting_finishes', 'Painting & Decorative Finishes'), ('furnishing_renovation', 'Furnishing & Renovation Contracts'), ('material_site_management', 'Material Supply & Site Management')], max_length=50),
        ),
    ]
